[package]
name = "executor_v2"
version = "0.0.1"

[addresses]
executor_v2 = "c929703bae20615775e77e8865e987dc8b9c222a2806e969a63db141743b6efc"

[dependencies]
layerzero_common = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="layerzero-common", rev="main" }
executor_auth = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="executor/executor-auth", rev="main" }
