[package]
name = "layerzero"
version = "0.0.1"

[addresses]
layerzero = "c929703bae20615775e77e8865e987dc8b9c222a2806e969a63db141743b6efc"
test = "0x8"
lzapp = "0x9"

[dependencies]
layerzero_common = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="layerzero-common", rev="main" }
zro = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="zro", rev="main" }
msglib_auth = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="msglib/msglib-auth", rev="main" }
msglib_v2 = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="msglib/msglib-v2", rev="main" }
msglib_v1_1 = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="msglib/msglib-v1/msglib-v1-1", rev="main" }
executor_auth = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="executor/executor-auth", rev="main" }
executor_v2 = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="executor/executor-v2", rev="main" }