[package]
name = "zro"
version = "0.0.1"

[addresses]
zro = "0xcf1926d4924eb6b664af1107ed7bf5a2d906d1edde09bc6726f89a2c7176bc0f"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "895ae28e4a105430d8b9d2ce2f6e48c3b2c7fcf0"