[package]
name = "msglib_v1_1"
version = "0.0.1"

[addresses]
msglib_v1_1 = "c929703bae20615775e77e8865e987dc8b9c222a2806e969a63db141743b6efc"

[dependencies]
layerzero_common = {  git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="layerzero-common", rev="main"}
msglib_auth = {  git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="msglib/msglib-auth", rev="main"}
zro = {  git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir="zro", rev="main"}
