[package]
name = "layerzero_apps"
version = "0.0.1"

[addresses]
layerzero_apps = "c929703bae20615775e77e8865e987dc8b9c222a2806e969a63db141743b6efc"

[dependencies]
layerzero = { git = "https://github.com/kairoski03/LayerZero-Aptos-Contract.git", subdir = "layerzero", rev = "main" }