[package]
name = "layerzero_common"
version = "0.0.1"

[addresses]
layerzero_common = "c929703bae20615775e77e8865e987dc8b9c222a2806e969a63db141743b6efc"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "testnet"